version: '3.4'

x-common:
  &common
  volumes:
    - .:/code
  environment:
    DJANGO_SETTINGS_MODULE: 'lw.core.settings.dev'
    DB_NAME: 'lw'
    DB_USER: 'root'
    DB_PASSWORD: ''

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql.conf.d:/etc/mysql/conf.d

  app:
    << : *common
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./manage.py runserver 0.0.0.0:80
    ports:
      - "127.0.0.1:8020:80"
    depends_on:
      - db
    restart: always
