apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: {{ .Values.django.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: django
          image: {{ .Values.django.image }}:{{ .Values.django.version }}
          ports:
            - containerPort: {{ .Values.django.containerPort }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'lw.core.settings.production'
            - name: DB_NAME
              value: 'lw'
            - name: DB_USER
              value: 'lw'
            - name: DB_HOST   
              value: mariadb-release
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret_key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: lw_user_password
          resources:
            limits:
              memory: 300Mi
