apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      imagePullSecrets:
        - name: registry

      volumes:
        - name: assets-volume
          emptyDir: {}

      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}:{{ .Values.version }}
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
          volumeMounts:
            - name: assets-volume
              mountPath: /static

        - name: django
          image: {{ .Values.django.image }}:{{ .Values.version }}
          ports:
            - containerPort: {{ .Values.django.containerPort }}
          volumeMounts:
            - name: assets-volume
              mountPath: /code/lw/static

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 3

          startupProbe:
            timeoutSeconds: 10
            exec:
              command:
                - make
                - prepare_container
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'lw.core.settings.production'
            - name: DB_NAME
              value: 'lw'
            - name: DB_USER
              value: 'lw'
            - name: DB_HOST
              value: mariadb-release
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret_key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: lw_user_password
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
