apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    app: django-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: django-app
